### ISSUE TITLE
[Discussion] Issues and Enhancement of Unit Tests of Core p5

### ISSUE THREAD

**Issue by sakshamsaxena** [processing/p5.js#2028]
#### Nature of issue?

- [x] Existing feature enhancement

#### Most appropriate sub-area of p5.js?

- [x] Core

#### Feature enhancement details:
Some *Unit Tests of Core* are written slightly off the Core itself, apparently, especially in [`renderer.js`](https://github.com/processing/p5.js/blob/master/test/unit/core/renderer.js) and [`structure.js`](https://github.com/processing/p5.js/blob/master/test/unit/core/structure.js). I thought it's best to summarise them in a single issue rather than open a separate one for each, for most of them are fairly small and interrelated. 

- [x] If I'm not wrong, `strokeWeight()` test is [described as fill color on L#22](https://github.com/processing/p5.js/blob/master/test/unit/core/renderer.js#L22). Typo ? 
- [ ] `stroke()` itself isn't defined in the core *attributes*, whereas `strokeJoin()` is. Unless the usage of former is intentional, I suggest modifying [this test case on L#29](https://github.com/processing/p5.js/blob/master/test/unit/core/renderer.js#L29) for `strokeCap()` ? Blend tests also require a little sketch whose definition [here on L#49](https://github.com/processing/p5.js/blob/master/test/unit/core/renderer.js#L49) uses `stroke()`, which is currently a part of Color. For enhanced modularity, can we discuss shifting particularly the `stroke()` function to core ?
- [x] `textSize()` is a part of Typography, but only this attribute from that area is tested [here at L#41](https://github.com/processing/p5.js/blob/master/test/unit/core/renderer.js#L41). Is it necessary to check for this, or the other text attributes are still left to be tested here ? Or maybe we can shift all the text related tests to typography's unit test ?
- [x] There's a suite on `get()` in rendering test suite, but it's a part of Image, and doesn't really appeal to me like an apt test. It's loosely written too, and is fairly ancient.
- [x] Teardown [here in structure.js](https://github.com/processing/p5.js/blob/master/test/unit/core/structure.js#L9) should have `remove()` instead of `clear()` I think ?
- [x] The only suite in `structure.js` focuses on push and pop almost superfluously, in my opinion. Can also include a little suite on `loop() and noLoop()` etc with bare minimum test cases.

**Comment by lmccart** [comment]
@sakshamsaxena regarding the open point.. stroke() and fill() are more complex attributes and need to be in their own module (currently in color/setting). however, I think all the files in the color/ dir should probably be part of the core or base module.

**Comment by sakshamsaxena** [comment]
Final Bottleneck in Core Tests :

`new p5() / global mode` Suite :
There is a `_globalInit` function attachment to window which is defined in the `app.js`. However, since I'm not targeting that file at all, I am missing out only on this `_globalInit` function, which fails the suite. 

Is it a good idea to use the same in the setup of the suite ?

**Comment by lmccart** [comment]
I think these have all been addressed now, closing this issue. Please reopen if I'm mistaken..
